# # This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
# version: 2.1

# orbs:
#   node: circleci/node@4.1

# workflows:
#   sample:
#     jobs:
#       - node/test:
#           version: '15.1'
#           # This is the node version to use for the `cimg/node` tag
#           # Relevant tags can be found on the CircleCI Developer Hub
#           # https://circleci.com/developer/images/image/cimg/node


version: 2.1

orbs:
  coveralls: coveralls/coveralls@3.1.1
  node: circleci/node@4.1

jobs:
  build-1:
    executor:
      name: node/default

    steps:
      - checkout

      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test

      - coveralls/upload:
          parallel: true
          flag_name: Test 1
          verbose: true
  done:
    executor:
      name: node/default

    steps:
      - coveralls/upload:
          parallel_finished: true

workflows:
  test_parallel_then_upload:
    jobs:
      - build-1
      - done:
          requires: [build-1]